/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafinalproject;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author ASUS
 */
public class HomePage extends javax.swing.JFrame {
    private int ServerCurrentCond = 0;
    private int ClientCurrentCond = 0;
    private ArrayList<String> questions = new ArrayList<>();
    private String serverName_pass;
    private int server_maxClient;
    private Thread createServer;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        ShowRndWheel = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        ShowVote = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        ShowRate = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        ShowLogin = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        CLIENTWAITING = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        CLIENTRATE = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        SubmitAnswer = new javax.swing.JButton();
        CLIENTLOGIN = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        clientINname = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        clientINpass = new javax.swing.JPasswordField();
        jPanel41 = new javax.swing.JPanel();
        ClientLogInError = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        CLIENTJOIN = new javax.swing.JButton();
        SERVERWAITING = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        ServerShowResult = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        currentClient = new javax.swing.JTextField();
        SERVERCREATERATE = new javax.swing.JPanel();
        SERVERCREATEVOTEONE = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roomNameCreate = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        passwordCreate = new javax.swing.JPasswordField();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionArea = new javax.swing.JTextArea();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        maxClient = new javax.swing.JSpinner();
        jPanel48 = new javax.swing.JPanel();
        ServerCreateRoomError = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        RateCreateRoom = new javax.swing.JButton();
        VOTE = new javax.swing.JPanel();
        RANDOM_WHEEL = new javax.swing.JPanel();
        RATERESULT = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 400));

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROJECT");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ASSISTANCE");
        jPanel5.add(jLabel4);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        ShowRndWheel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ShowRndWheel.setText("RANDOM WHEEL");
        ShowRndWheel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ShowRndWheel.setPreferredSize(new java.awt.Dimension(150, 30));
        ShowRndWheel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRndWheelActionPerformed(evt);
            }
        });
        jPanel8.add(ShowRndWheel, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel8);

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        ShowVote.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ShowVote.setText("VOTE");
        ShowVote.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ShowVote.setPreferredSize(new java.awt.Dimension(150, 30));
        ShowVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowVoteActionPerformed(evt);
            }
        });
        jPanel12.add(ShowVote, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 51, 51));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        ShowRate.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ShowRate.setText("RATE");
        ShowRate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ShowRate.setPreferredSize(new java.awt.Dimension(150, 30));
        ShowRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRateActionPerformed(evt);
            }
        });
        jPanel13.add(ShowRate, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(0, 51, 51));
        jPanel14.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        ShowLogin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ShowLogin.setText("LOGIN");
        ShowLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ShowLogin.setPreferredSize(new java.awt.Dimension(150, 30));
        ShowLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowLoginActionPerformed(evt);
            }
        });
        jPanel14.add(ShowLogin, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel14);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jLayeredPane1.setBackground(new java.awt.Color(255, 204, 255));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(550, 400));
        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        CLIENTWAITING.setLayout(new java.awt.GridBagLayout());

        jPanel39.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel39.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel39.setLayout(new java.awt.BorderLayout());

        jPanel40.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel40.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel14.setText("Rating Complete!");
        jPanel40.add(jLabel14, new java.awt.GridBagConstraints());

        jPanel39.add(jPanel40, java.awt.BorderLayout.PAGE_START);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel15.setText("Please Wait for the result");
        jPanel42.add(jLabel15);

        jPanel39.add(jPanel42, java.awt.BorderLayout.CENTER);

        CLIENTWAITING.add(jPanel39, new java.awt.GridBagConstraints());

        jLayeredPane1.add(CLIENTWAITING);

        CLIENTRATE.setLayout(new java.awt.BorderLayout());

        jPanel32.setBackground(new java.awt.Color(153, 153, 153));
        jPanel32.setPreferredSize(new java.awt.Dimension(592, 50));
        jPanel32.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel12.setText("PLEASE ANSWER THE FOLLOWING QUESTION");
        jPanel32.add(jLabel12, new java.awt.GridBagConstraints());

        CLIENTRATE.add(jPanel32, java.awt.BorderLayout.PAGE_START);

        jPanel37.setBackground(new java.awt.Color(153, 153, 153));
        jPanel37.setPreferredSize(new java.awt.Dimension(592, 50));
        jPanel37.setLayout(new java.awt.GridBagLayout());

        SubmitAnswer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        SubmitAnswer.setText("SUBMIT");
        SubmitAnswer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitAnswer.setPreferredSize(new java.awt.Dimension(150, 30));
        SubmitAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAnswerActionPerformed(evt);
            }
        });
        jPanel37.add(SubmitAnswer, new java.awt.GridBagConstraints());

        CLIENTRATE.add(jPanel37, java.awt.BorderLayout.PAGE_END);

        jLayeredPane1.add(CLIENTRATE);

        CLIENTLOGIN.setBackground(new java.awt.Color(204, 204, 204));
        CLIENTLOGIN.setMaximumSize(new java.awt.Dimension(591, 500));
        CLIENTLOGIN.setPreferredSize(new java.awt.Dimension(550, 500));
        CLIENTLOGIN.setLayout(new java.awt.GridBagLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel26.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("JOIN RATING");
        jPanel26.add(jLabel9, new java.awt.GridBagConstraints());

        jPanel19.add(jPanel26, java.awt.BorderLayout.PAGE_START);

        jPanel27.setBackground(new java.awt.Color(153, 153, 153));

        jPanel36.setBackground(new java.awt.Color(153, 153, 153));
        jPanel36.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel36);

        jPanel28.setPreferredSize(new java.awt.Dimension(350, 55));
        jPanel28.setRequestFocusEnabled(false);
        jPanel28.setLayout(new java.awt.BorderLayout());

        jPanel29.setBackground(new java.awt.Color(153, 153, 153));
        jPanel29.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("Room Name :");
        jPanel29.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel28.add(jPanel29, java.awt.BorderLayout.NORTH);

        clientINname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientINnameActionPerformed(evt);
            }
        });
        jPanel28.add(clientINname, java.awt.BorderLayout.CENTER);

        jPanel27.add(jPanel28);

        jPanel30.setPreferredSize(new java.awt.Dimension(350, 55));
        jPanel30.setRequestFocusEnabled(false);
        jPanel30.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(153, 153, 153));
        jPanel31.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("Password :");
        jPanel31.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel31, java.awt.BorderLayout.NORTH);
        jPanel30.add(clientINpass, java.awt.BorderLayout.CENTER);

        jPanel27.add(jPanel30);

        jPanel41.setBackground(new java.awt.Color(153, 153, 153));
        jPanel41.setPreferredSize(new java.awt.Dimension(350, 17));
        jPanel41.setLayout(new java.awt.GridBagLayout());

        ClientLogInError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel41.add(ClientLogInError, new java.awt.GridBagConstraints());

        jPanel27.add(jPanel41);

        jPanel34.setBackground(new java.awt.Color(153, 153, 153));
        jPanel34.setPreferredSize(new java.awt.Dimension(150, 40));

        jPanel35.setBackground(new java.awt.Color(153, 153, 153));
        jPanel35.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel35.setLayout(new java.awt.GridLayout(1, 0));

        CLIENTJOIN.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        CLIENTJOIN.setText("JOIN ROOM");
        CLIENTJOIN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CLIENTJOIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIENTJOINActionPerformed(evt);
            }
        });
        jPanel35.add(CLIENTJOIN);

        jPanel34.add(jPanel35);

        jPanel27.add(jPanel34);

        jPanel19.add(jPanel27, java.awt.BorderLayout.CENTER);

        CLIENTLOGIN.add(jPanel19, new java.awt.GridBagConstraints());

        jLayeredPane1.add(CLIENTLOGIN);

        SERVERWAITING.setBackground(new java.awt.Color(153, 153, 153));
        SERVERWAITING.setLayout(new java.awt.GridBagLayout());

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel22.setLayout(new java.awt.BorderLayout());

        jPanel23.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel23.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel7.setText("WAITING...");
        jPanel23.add(jLabel7, new java.awt.GridBagConstraints());

        jPanel22.add(jPanel23, java.awt.BorderLayout.PAGE_START);

        jPanel24.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel24.setLayout(new java.awt.GridBagLayout());

        ServerShowResult.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        ServerShowResult.setText("STOP & SHOW RESULT");
        ServerShowResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ServerShowResult.setPreferredSize(new java.awt.Dimension(165, 30));
        ServerShowResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerShowResultActionPerformed(evt);
            }
        });
        jPanel24.add(ServerShowResult, new java.awt.GridBagConstraints());

        jPanel22.add(jPanel24, java.awt.BorderLayout.SOUTH);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setText("CURRENT RATED : ");
        jPanel25.add(jLabel8);

        currentClient.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        currentClient.setForeground(new java.awt.Color(51, 102, 255));
        currentClient.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currentClient.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        currentClient.setEnabled(false);
        currentClient.setMinimumSize(new java.awt.Dimension(55, 26));
        currentClient.setPreferredSize(new java.awt.Dimension(55, 26));
        currentClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentClientActionPerformed(evt);
            }
        });
        jPanel25.add(currentClient);

        jPanel22.add(jPanel25, java.awt.BorderLayout.CENTER);

        SERVERWAITING.add(jPanel22, new java.awt.GridBagConstraints());

        jLayeredPane1.add(SERVERWAITING);

        SERVERCREATERATE.setBackground(new java.awt.Color(204, 204, 204));
        SERVERCREATERATE.setMaximumSize(new java.awt.Dimension(591, 500));
        SERVERCREATERATE.setPreferredSize(new java.awt.Dimension(550, 500));
        SERVERCREATERATE.setLayout(new java.awt.GridBagLayout());

        SERVERCREATEVOTEONE.setBackground(new java.awt.Color(204, 204, 204));
        SERVERCREATEVOTEONE.setMaximumSize(new java.awt.Dimension(591, 500));
        SERVERCREATEVOTEONE.setPreferredSize(new java.awt.Dimension(550, 500));
        SERVERCREATEVOTEONE.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("CREATE A ROOM");
        jPanel7.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        jPanel10.setPreferredSize(new java.awt.Dimension(350, 45));
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Room Name :");
        jPanel11.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11, java.awt.BorderLayout.NORTH);

        roomNameCreate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        roomNameCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNameCreateActionPerformed(evt);
            }
        });
        jPanel10.add(roomNameCreate, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10);

        jPanel15.setPreferredSize(new java.awt.Dimension(350, 45));
        jPanel15.setRequestFocusEnabled(false);
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Set Password :");
        jPanel16.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel16, java.awt.BorderLayout.NORTH);

        passwordCreate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel15.add(passwordCreate, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel15);

        jPanel17.setPreferredSize(new java.awt.Dimension(350, 70));
        jPanel17.setRequestFocusEnabled(false);
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));
        jPanel18.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("Question :");
        jPanel18.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel18, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        questionArea.setColumns(20);
        questionArea.setRows(5);
        jScrollPane1.setViewportView(questionArea);

        jPanel17.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel17);

        jPanel46.setPreferredSize(new java.awt.Dimension(350, 45));
        jPanel46.setLayout(new java.awt.BorderLayout());

        jPanel47.setBackground(new java.awt.Color(153, 153, 153));
        jPanel47.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel47.setLayout(new java.awt.BorderLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel20.setText("Maximum Participant :");
        jPanel47.add(jLabel20, java.awt.BorderLayout.CENTER);

        jPanel46.add(jPanel47, java.awt.BorderLayout.NORTH);

        maxClient.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        maxClient.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jPanel46.add(maxClient, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel46);

        jPanel48.setBackground(new java.awt.Color(153, 153, 153));
        jPanel48.setPreferredSize(new java.awt.Dimension(350, 17));
        jPanel48.setLayout(new java.awt.GridBagLayout());

        ServerCreateRoomError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel48.add(ServerCreateRoomError, new java.awt.GridBagConstraints());

        jPanel9.add(jPanel48);

        jPanel20.setBackground(new java.awt.Color(153, 153, 153));
        jPanel20.setPreferredSize(new java.awt.Dimension(150, 40));

        jPanel21.setBackground(new java.awt.Color(153, 153, 153));
        jPanel21.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel21.setLayout(new java.awt.GridLayout(1, 0));

        RateCreateRoom.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        RateCreateRoom.setText("CREATE");
        RateCreateRoom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RateCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateCreateRoomActionPerformed(evt);
            }
        });
        jPanel21.add(RateCreateRoom);

        jPanel20.add(jPanel21);

        jPanel9.add(jPanel20);

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        SERVERCREATERATE.add(jPanel3, new java.awt.GridBagConstraints());

        voteOneSystem temp=new voteOneSystem();
        SERVERCREATEVOTEONE.add(temp.sideA, new java.awt.GridBagConstraints());

        jLayeredPane1.add(SERVERCREATERATE);
        jLayeredPane1.add(SERVERCREATEVOTEONE);

        // VOTE.setBackground(new java.awt.Color(0, 204, 204));
        // VOTE.setMaximumSize(new java.awt.Dimension(591, 500));
        // VOTE.setPreferredSize(new java.awt.Dimension(591, 500));

        // javax.swing.GroupLayout VOTELayout = new javax.swing.GroupLayout(VOTE);
        // VOTE.setLayout(VOTELayout);
        // VOTELayout.setHorizontalGroup(
        //     VOTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        //     .addGap(0, 591, Short.MAX_VALUE)
        // );
        // VOTELayout.setVerticalGroup(
        //     VOTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        //     .addGap(0, 402, Short.MAX_VALUE)
        // );

        // jLayeredPane1.add(VOTE);

        RANDOM_WHEEL.setBackground(new java.awt.Color(255, 204, 204));
        RANDOM_WHEEL.setMaximumSize(new java.awt.Dimension(591, 500));
        RANDOM_WHEEL.setPreferredSize(new java.awt.Dimension(550, 500));

        javax.swing.GroupLayout RANDOM_WHEELLayout = new javax.swing.GroupLayout(RANDOM_WHEEL);
        RANDOM_WHEEL.setLayout(RANDOM_WHEELLayout);
        RANDOM_WHEELLayout.setHorizontalGroup(
            RANDOM_WHEELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        RANDOM_WHEELLayout.setVerticalGroup(
            RANDOM_WHEELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jLayeredPane1.add(RANDOM_WHEEL);

        RATERESULT.setBackground(new java.awt.Color(204, 204, 204));
        RATERESULT.setLayout(new java.awt.BorderLayout());

        jPanel43.setPreferredSize(new java.awt.Dimension(592, 50));
        jPanel43.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel43.add(jButton1, new java.awt.GridBagConstraints());

        RATERESULT.add(jPanel43, java.awt.BorderLayout.PAGE_END);

        jLayeredPane1.add(RATERESULT);

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowVoteActionPerformed
        // TODO add your handling code here:
        RANDOM_WHEEL.setVisible(false);
        SERVERCREATEVOTEONE.setVisible(true);
        SERVERCREATERATE.setVisible(false);
        SERVERWAITING.setVisible(false);
        CLIENTLOGIN.setVisible(false);
        CLIENTRATE.setVisible(false);
        CLIENTWAITING.setVisible(false);
        RATERESULT.setVisible(false);
    }//GEN-LAST:event_ShowVoteActionPerformed

    private void ShowRndWheelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRndWheelActionPerformed
        // TODO add your handling code here:
        RANDOM_WHEEL.setVisible(true);
        SERVERCREATEVOTEONE.setVisible(false);
        SERVERCREATERATE.setVisible(false);
        SERVERWAITING.setVisible(false);
        CLIENTLOGIN.setVisible(false);
        CLIENTRATE.setVisible(false);
        CLIENTWAITING.setVisible(false);
        RATERESULT.setVisible(false);
    }//GEN-LAST:event_ShowRndWheelActionPerformed

    private void ShowRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRateActionPerformed
        // TODO add your handling code here:
        if(ServerCurrentCond == 0) {
            SERVERCREATERATE.setVisible(true);
            SERVERCREATEVOTEONE.setVisible(false);
            SERVERWAITING.setVisible(false);
            RATERESULT.setVisible(false);
        }
        else if (ServerCurrentCond == 1) {
            SERVERCREATERATE.setVisible(false);
            SERVERCREATEVOTEONE.setVisible(false);
            SERVERWAITING.setVisible(true);
            RATERESULT.setVisible(false);
        }
        else if(ServerCurrentCond == 2) {
            SERVERCREATERATE.setVisible(false);
            SERVERCREATEVOTEONE.setVisible(false);
            SERVERWAITING.setVisible(false);
            RATERESULT.setVisible(true);
        }
        RANDOM_WHEEL.setVisible(false);
        SERVERCREATEVOTEONE.setVisible(false);
        CLIENTLOGIN.setVisible(false);
        CLIENTRATE.setVisible(false);
        CLIENTWAITING.setVisible(false);
    }//GEN-LAST:event_ShowRateActionPerformed

    private void ShowLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowLoginActionPerformed
        // TODO add your handling code here:
        if(ClientCurrentCond == 0) {
            CLIENTLOGIN.setVisible(true);
            CLIENTRATE.setVisible(false);
            CLIENTWAITING.setVisible(false);
            RATERESULT.setVisible(false);
        }
        else if(ClientCurrentCond == 1) {
            CLIENTLOGIN.setVisible(false);
            CLIENTRATE.setVisible(true);
            CLIENTWAITING.setVisible(false);
            RATERESULT.setVisible(false);
        }
        else if(ClientCurrentCond == 2) {
            CLIENTLOGIN.setVisible(false);
            CLIENTRATE.setVisible(false);
            CLIENTWAITING.setVisible(true);
            RATERESULT.setVisible(false);
        }
        else if(ClientCurrentCond == 3) {
            CLIENTLOGIN.setVisible(false);
            CLIENTRATE.setVisible(false);
            CLIENTWAITING.setVisible(false);
            RATERESULT.setVisible(true);
        }
        RANDOM_WHEEL.setVisible(false);
        SERVERCREATEVOTEONE.setVisible(false);
        SERVERCREATERATE.setVisible(false);
        SERVERWAITING.setVisible(false);
    }//GEN-LAST:event_ShowLoginActionPerformed

    private void roomNameCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNameCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNameCreateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TORANDOM_WHEEL.setVisible(false);DO add your handling code here:
        RANDOM_WHEEL.setVisible(false);
        SERVERCREATEVOTEONE.setVisible(false);
        SERVERCREATERATE.setVisible(false);
        SERVERWAITING.setVisible(false);
        CLIENTLOGIN.setVisible(false);
        CLIENTRATE.setVisible(false);
        CLIENTWAITING.setVisible(false);
        RATERESULT.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void RateCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateCreateRoomActionPerformed
        // TODO add your handling code here:
        if(checkData()) {
            SERVERWAITING.setVisible(true);
            SERVERCREATERATE.setVisible(false);
            ServerCurrentCond = 1;
            
            serverName_pass = roomNameCreate.getText() + "_" + passwordCreate.getText();
//            Object selectedObject = maxClient.getSelectedItem();
//            String maxClientStr = selectedObject.toString();
            server_maxClient = (int) maxClient.getValue();
            
            ArrayList<String> questionList = extractSentences(questionArea);
            String questionListStr = questionList.toString();
            System.out.println(questionListStr);
            
            System.out.println(serverName_pass + " " + server_maxClient);
            
            Server.ChangeServerID(serverName_pass, server_maxClient, questionListStr, questionList.size());
            createServer = new Thread(() -> Server.startServer());
            createServer.start();
            Thread waiting = new Thread(() -> wait4Server());
            waiting.start();
        }

    }//GEN-LAST:event_RateCreateRoomActionPerformed

    private boolean checkData() {
        if(!roomNameCreate.getText().isEmpty() && passwordCreate.getText().length() != 0 && !questionArea.getText().isEmpty()) {
            return true;
        }else {
            ServerCreateRoomError.setText("Please fill in all data above!");
            return false;
        }
    }
    
    public static ArrayList<String> extractSentences(JTextArea textArea) {
        String text = textArea.getText().trim(); // Get the text from the JTextArea and remove leading/trailing whitespace
        String[] sentences = text.split("\\R"); // Split the text by line breaks (platform-independent regex)

        ArrayList<String> sentenceList = new ArrayList<>();
        for (String sentence : sentences) {
            sentenceList.add(sentence.trim()); // Add each sentence to the ArrayList (removing leading/trailing whitespace)
        }

        return sentenceList;
    }
    
    public void wait4Server() {
        
        while (true) {
            currentClient.setText(Integer.toString(Server.getCurrentClient()));

            if(Integer.parseInt(currentClient.getText()) == server_maxClient) {
                int[][] result = Server.getResult();
                ArrayList<String> ques = convertStringToArrayList(Server.getQuestions());
                
                System.out.println("Question :");
                printArrayList(ques);
                
                System.out.println("Result = ");
                printArray(result);
                
                createResultField(ques, result); 
                
                SERVERWAITING.setVisible(false);
                RATERESULT.setVisible(true);
                ServerCurrentCond = 2;
                break;
            }
            try {
                Thread.sleep(1000); // Sleep for 1 second
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        
//        try{
//            createServer.join();
//            int[][] result = Server.getResult();
//            System.out.println("Rating Complete!");
//        }catch(InterruptedException e){
//            e.printStackTrace();
//        }
    }
    
    private void clientINnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientINnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientINnameActionPerformed

    private void CLIENTJOINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIENTJOINActionPerformed
        // TODO add your handling code here:
        if(checkClientData()) {
            createQuestionField(convertStringToArrayList(Client.getQuestions()));
            CLIENTLOGIN.setVisible(false);
            CLIENTRATE.setVisible(true);    
            ClientCurrentCond = 1;
        }
    }//GEN-LAST:event_CLIENTJOINActionPerformed

    public static ArrayList<String> convertStringToArrayList(String arrayListAsString) {
        // Remove the square brackets from the string representation
        String cleanString = arrayListAsString.substring(1, arrayListAsString.length() - 1);

        // Split the string by commas to get individual elements
        String[] elements = cleanString.split(", ");

        // Convert the array of strings to an ArrayList
        List<String> list = Arrays.asList(elements);
        return new ArrayList<>(list);
    }
    
    private void createQuestionField(ArrayList<String> questions) {
        JPanel questionPanel = new CreateQuestionsList(questions);
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setPreferredSize(new Dimension(450, 350));
        scrollPane.setViewportView(questionPanel);
        
        CLIENTRATE.add(scrollPane, BorderLayout.CENTER);
    }
    
    private boolean checkClientData() {
        int condition = Client.connectToServer(clientINname.getText(), clientINpass.getText());
        
        if(condition == 1)
            return true;
        else{
            ClientLogInError.setText("Invalid Server Name or Password");
            return false;
        }
    }
    
    private void SubmitAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAnswerActionPerformed
        // TODO add your handling code here:
        ArrayList<Integer> result = getLatestSliderValues(CreateQuestionsList.getSliders());
        Client.setResult(result.toString());
        System.out.println(result);
        
        CLIENTRATE.setVisible(false);
        CLIENTWAITING.setVisible(true);
        ClientCurrentCond = 2;
        
        Thread ClientWaiting = new Thread(() -> clientWaiting4Result());
        ClientWaiting.start();
    }//GEN-LAST:event_SubmitAnswerActionPerformed
    public static ArrayList<Integer> getLatestSliderValues(ArrayList<JSlider> sliders) {
        ArrayList<Integer> sliderValues = new ArrayList<>();
        
        for (JSlider slider : sliders) {
            int value = slider.getValue();
            sliderValues.add(value);
        }
        
        return sliderValues;
    }
    
    public static void printArrayList(ArrayList<String> arrayList){
        for(String x : arrayList){
            System.out.println(x);
        }
    }
    
    public static void printArray(int[][] array) {
        for(int[] row : array){
            System.out.println(Arrays.toString(row));
        }
    }
    
    private void createResultField(ArrayList<String> questions, int[][] result) {
        JPanel resultPanel = new CreateChartList(questions, result);
        
        System.out.println(Client.getQuestions());
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setPreferredSize(new Dimension(450, 350));
        scrollPane.setViewportView(resultPanel);
        
        RATERESULT.add(scrollPane, BorderLayout.CENTER);
    }
    
    public void clientWaiting4Result(){
        if(Client.getFinalResult()){
            System.out.println("Result Received");
            
            int[][] result = Client.getResult();
            ArrayList<String> ques = convertStringToArrayList(Client.getQuestions());
            
                System.out.println("Question :");
                printArrayList(ques);
                
                System.out.println("Result = ");
                printArray(result);
            
                createResultField(ques, result);          
            
            CLIENTWAITING.setVisible(false);
            RATERESULT.setVisible(true);
            ClientCurrentCond = 3;
        }
    }
    private void ServerShowResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerShowResultActionPerformed
        // TODO add your handling code here:
        server_maxClient = Server.getCurrentClient();
        Server.stopReceivingClient();
    }//GEN-LAST:event_ServerShowResultActionPerformed

    private void currentClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentClientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RANDOM_WHEEL.setVisible(false);
        SERVERCREATEVOTEONE.setVisible(false);
        SERVERCREATERATE.setVisible(false);
        SERVERWAITING.setVisible(false);
        CLIENTLOGIN.setVisible(false);
        CLIENTRATE.setVisible(false);
        CLIENTWAITING.setVisible(false);
        RATERESULT.setVisible(false);
        ServerCurrentCond = 0;
        ClientCurrentCond = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLIENTJOIN;
    private javax.swing.JPanel CLIENTLOGIN;
    private javax.swing.JPanel CLIENTRATE;
    private javax.swing.JPanel CLIENTWAITING;
    private javax.swing.JLabel ClientLogInError;
    private javax.swing.JPanel RANDOM_WHEEL;
    private javax.swing.JPanel RATERESULT;
    private javax.swing.JButton RateCreateRoom;
    private javax.swing.JPanel SERVERCREATERATE;
    private javax.swing.JPanel SERVERCREATEVOTEONE;
    private javax.swing.JPanel SERVERWAITING;
    private javax.swing.JLabel ServerCreateRoomError;
    private javax.swing.JButton ServerShowResult;
    private javax.swing.JButton ShowLogin;
    private javax.swing.JButton ShowRate;
    private javax.swing.JButton ShowRndWheel;
    private javax.swing.JButton ShowVote;
    private javax.swing.JButton SubmitAnswer;
    private javax.swing.JPanel VOTE;
    private javax.swing.JTextField clientINname;
    private javax.swing.JPasswordField clientINpass;
    private javax.swing.JTextField currentClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner maxClient;
    private javax.swing.JPasswordField passwordCreate;
    private javax.swing.JTextArea questionArea;
    private javax.swing.JTextField roomNameCreate;
    // End of variables declaration//GEN-END:variables
}
